name: API Tests (TS)
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run test:ci
      - name: Generate Allure
        if: always()
        run: |
          npx allure generate reports/allure-results -o reports/allure-report || true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: reports/allure-report
